//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicQueries.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InputSchemaMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputSchemaMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicQueries.Core.Resources.InputSchemaMessages", typeof(InputSchemaMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la fuente de datos a consultar.
        /// </summary>
        internal static string DataSourceDescription {
            get {
                return ResourceManager.GetString("DataSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos a seleccionar (opcional)..
        /// </summary>
        internal static string FieldNamesDescription {
            get {
                return ResourceManager.GetString("FieldNamesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros de la consulta..
        /// </summary>
        internal static string FiltersDescription {
            get {
                return ResourceManager.GetString("FiltersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo sobre el cual se aplicará el filtro..
        /// </summary>
        internal static string FiltersFieldNameDescription {
            get {
                return ResourceManager.GetString("FiltersFieldNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor opcional para unir el siguiente filtro..
        /// </summary>
        internal static string FiltersJoinWithNextDescription {
            get {
                return ResourceManager.GetString("FiltersJoinWithNextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operadores disponibles..
        /// </summary>
        internal static string FiltersOperationDescription {
            get {
                return ResourceManager.GetString("FiltersOperationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor del filtro a aplicar..
        /// </summary>
        internal static string FiltersValueDescription {
            get {
                return ResourceManager.GetString("FiltersValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campos sobres los cuales se aplica el ordenamiento..
        /// </summary>
        internal static string OrdersDescription {
            get {
                return ResourceManager.GetString("OrdersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo sobre el cual se ordenará..
        /// </summary>
        internal static string OrdersFieldNameDescription {
            get {
                return ResourceManager.GetString("OrdersFieldNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección del ordenamiento (ascendente o desscendente)..
        /// </summary>
        internal static string OrdersOrdersTypeDescription {
            get {
                return ResourceManager.GetString("OrdersOrdersTypeDescription", resourceCulture);
            }
        }
    }
}
